version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root  # needed to install packages and access docker.sock
    restart: always
    ports:
      - "8080:8080"       # Jenkins UI
      - "50000:50000"     # JNLP agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # for Docker builds
      - /usr/bin/docker:/usr/bin/docker            # use host Docker CLI
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - jenkins-net

volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: bridge
